# Generated by Django 2.1 on 2020-08-07 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checkin_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
