# Generated by Django 2.1 on 2020-08-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_checkin_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='canceled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='notification_text',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
