# Generated by Django 2.1 on 2020-08-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkin.Reason'),
        ),
    ]
