# Generated by Django 2.1 on 2020-08-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_checkin_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='vehicle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
