# Generated by Django 2.1 on 2020-08-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_textmessage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
