# Generated by Django 2.1 on 2020-08-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0009_auto_20200826_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
