# Generated by Django 2.1 on 2020-09-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0010_auto_20200826_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textmessage',
            old_name='title',
            new_name='subject',
        ),
    ]
