# Generated by Django 2.1 on 2020-09-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0012_auto_20200908_1026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
