# Generated by Django 2.1 on 2020-09-10 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0013_auto_20200908_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
