# Generated by Django 2.1 on 2020-09-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0014_delete_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, null=True)),
                ('to_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='subject',
            field=models.CharField(blank=True, choices=[('check in page', 'Check In Page'), ('ready notification', 'Ready Notification'), ('first contact', 'First Contact SMS'), ('invalid response', 'Invalid Response'), ('already_checked_in_response', 'Already Checked-in Response'), ('cancellation_response', 'Cancellation Response'), ('invalid_cancellation_request', 'Invalid Cancellation Request')], max_length=120, null=True),
        ),
    ]
