# Generated by Django 2.1 on 2020-09-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0015_auto_20200915_0126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwilioMessages',
        ),
    ]
