# Generated by Django 2.1 on 2020-09-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0016_delete_twiliomessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, null=True)),
                ('to_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
