# Generated by Django 2.1 on 2020-09-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0018_twiliomessages_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twiliomessages',
            old_name='to_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='twiliomessages',
            name='type',
        ),
        migrations.AlterField(
            model_name='twiliomessages',
            name='message_sid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
