# Generated by Django 2.1 on 2020-09-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0019_auto_20200915_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twiliomessages',
            old_name='message_sid',
            new_name='incoming_message_sid',
        ),
        migrations.AddField(
            model_name='twiliomessages',
            name='sent_message_sid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
